# Generated by Django 4.2 on 2023-05-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_delete_avisclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('afficher', models.BooleanField(default=False)),
                ('photo', models.ImageField(default='22.png', upload_to='photodeprofil/')),
            ],
        ),
    ]
