# Generated by Django 3.2.18 on 2023-04-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinformation',
            name='products',
            field=models.ManyToManyField(to='produits.Product'),
        ),
    ]
