# Generated by Django 3.2.18 on 2023-04-07 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_orderinformation_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_information',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='produits.orderinformation'),
            preserve_default=False,
        ),
    ]
