# Generated by Django 3.2.18 on 2023-04-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_alter_orderitem_order_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_information',
        ),
    ]
