# Generated by Django 3.2.18 on 2023-04-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_orderitem_order_information'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Panier'},
        ),
        migrations.AlterModelOptions(
            name='orderinformation',
            options={'verbose_name_plural': 'Les Commandes'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'PanierItem'},
        ),
        migrations.RemoveField(
            model_name='orderinformation',
            name='products',
        ),
    ]
