# Generated by Django 4.2 on 2023-04-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0008_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='colliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(default='bague.jpg', upload_to='product/')),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
