# Generated by Django 3.2.18 on 2023-04-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0009_colliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinformation',
            name='est_annullé',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='colliers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/MEDIA_ROOT/products/'),
        ),
    ]
