# Generated by Django 4.2 on 2023-04-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0010_auto_20230415_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('afficher', models.BooleanField(default=False)),
                ('photo', models.ImageField(default='22.png', upload_to='photodeprofil/')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemin_image', models.ImageField(upload_to='imagessssss/')),
                ('legende', models.CharField(max_length=20)),
                ('lien', models.URLField()),
            ],
        ),
    ]
