# Generated by Django 4.2 on 2023-04-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0011_avisclient_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='colliers',
        ),
    ]
