# Generated by Django 3.2.18 on 2023-04-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0012_delete_colliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorie',
            field=models.CharField(choices=[('collier', 'Collier'), ('bague', 'Bague'), ('braclet', 'Braclet'), ('montre', 'Montre'), ('boucles', 'Boucles'), ('totbag_bag', 'Totbag_bag'), ('argent', 'Argent'), ('parrure', 'Parrure')], default='OT', max_length=20),
        ),
    ]
