# Generated by Django 3.2.18 on 2023-04-26 15:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produits', '0014_wishlistitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishlistItem',
            new_name='Wishlist',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='added_date',
            new_name='added_at',
        ),
    ]
