# Generated by Django 3.2.18 on 2023-04-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0015_auto_20230426_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='added_at',
            new_name='added_date',
        ),
    ]
