# Generated by Django 4.2 on 2023-05-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0018_alter_orderitem_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvisClient',
        ),
    ]
