# Generated by Django 4.1.7 on 2023-03-27 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_customuser_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
