# Generated by Django 4.1.7 on 2023-03-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
